spring:
  application:
    name: auth-service
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ace_test
    username: root
    password: 7777
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    
#  cloud:
#    config:
#      uri: http://localhost:8888
      
#  profiles:
#    active: dev


server:
  port: 9000
  
#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka